name: frontend
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true



  # Custom fonts
  fonts:
    - family: "Tilt Warp"
      fonts:
        - asset: assets/TiltWarp-Bold.ttf
          weight: 700

    - family: "Comfortaa"
      fonts:
        - asset: assets/Comfortaa-Regular.ttf
          weight: 400
